# Generated by Django 4.2.7 on 2025-11-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_product_is_featured"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(default="متجر الملابس", max_length=100)),
                ("site_description", models.TextField(blank=True, max_length=500)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_address", models.TextField(blank=True)),
                (
                    "homepage_title",
                    models.CharField(
                        default="متجر الملابس - أحدث صيحات الموضة", max_length=200
                    ),
                ),
                ("featured_stores_count", models.PositiveIntegerField(default=6)),
                ("featured_products_count", models.PositiveIntegerField(default=8)),
                (
                    "delivery_fee",
                    models.DecimalField(decimal_places=2, default=15.0, max_digits=10),
                ),
                (
                    "free_delivery_threshold",
                    models.DecimalField(decimal_places=2, default=200.0, max_digits=10),
                ),
                ("facebook_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("primary_color", models.CharField(default="#667eea", max_length=7)),
                ("secondary_color", models.CharField(default="#764ba2", max_length=7)),
            ],
            options={
                "verbose_name": "إعدادات الموقع",
                "verbose_name_plural": "إعدادات الموقع",
            },
        ),
    ]
