# Generated by Django 4.2.7 on 2025-11-22 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_sitesettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="footer_copyright",
            field=models.CharField(default="جميع الحقوق محفوظة", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_description",
            field=models.TextField(
                default="نوفر لك أفضل المنتجات بأعلى جودة وأفضل الأسعار", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_link_1",
            field=models.CharField(default="المتاجر", max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_link_1_url",
            field=models.CharField(default="/stores/", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_link_2",
            field=models.CharField(default="الأكثر مبيعاً", max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_link_2_url",
            field=models.CharField(default="/products/most-sold/", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_link_3",
            field=models.CharField(default="العروض الخاصة", max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_link_3_url",
            field=models.CharField(default="/offers/", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_store_name",
            field=models.CharField(default="متجر الملابس", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_tagline",
            field=models.CharField(
                default="تسوق بثقة وأمان من أفضل المتاجر", max_length=200
            ),
        ),
    ]
