# Generated by Django 4.2.7 on 2025-11-23 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_sitesettings_footer_copyright_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="footer_link_3_url",
            field=models.CharField(default="/featured-products/", max_length=100),
        ),
        migrations.AlterField(
            model_name="store",
            name="owner",
            field=models.ForeignKey(
                limit_choices_to={"role": "admin"},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("customer", "عميل"), ("admin", "مدير")],
                default="customer",
                max_length=20,
            ),
        ),
    ]
