# Generated by Django 4.2.7 on 2025-11-23 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_sitesettings_footer_link_3_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="owner_key",
            field=models.CharField(
                blank=True, help_text="مفتاح خاص للمالك فقط", max_length=50
            ),
        ),
    ]
