# Generated by Django 4.2.7 on 2025-11-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_user_owner_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="rating",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name="store",
            name="category",
            field=models.CharField(
                choices=[
                    ("clothing", "ملابس"),
                    ("electronics", "إلكترونيات"),
                    ("food", "مطاعم"),
                    ("home", "منزل"),
                    ("beauty", "جمال"),
                    ("watches", "ساعات"),
                    ("sports", "رياضة"),
                    ("books", "كتب"),
                    ("toys", "ألعاب"),
                ],
                default="clothing",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="delivery_fee",
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="store",
            name="delivery_time",
            field=models.CharField(default="30-45 دقيقة", max_length=50),
        ),
        migrations.AddField(
            model_name="store",
            name="rating",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("men", "رجالي"),
                    ("women", "نسائي"),
                    ("kids", "أطفال"),
                    ("sports", "رياضية"),
                    ("casual", "كاجوال"),
                    ("formal", "رسمية"),
                    ("accessories", "إكسسوارات"),
                    ("electronics", "إلكترونيات"),
                    ("beauty", "جمال"),
                    ("watches", "ساعات"),
                ],
                max_length=20,
            ),
        ),
    ]
