# Generated by Django 4.2.7 on 2025-12-07 00:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_product_discount_price_product_rating_store_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "banner_image",
                    models.ImageField(blank=True, null=True, upload_to="campaigns/"),
                ),
                (
                    "discount_percent",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("is_active", models.BooleanField(default=False)),
                (
                    "action_url",
                    models.CharField(blank=True, default="/stores/", max_length=255),
                ),
            ],
            options={
                "verbose_name": "حملة",
                "verbose_name_plural": "حملات",
            },
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="contact_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="privacy_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="terms_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="store",
            name="category",
            field=models.CharField(
                choices=[
                    ("women", "ملابس نسائية"),
                    ("men", "ملابس رجالية"),
                    ("kids", "ملابس أطفال"),
                    ("perfumes", "عطور"),
                    ("cosmetics", "كوزمتك"),
                    ("watches", "ساعات"),
                    ("clothing", "ملابس عامة"),
                    ("electronics", "إلكترونيات"),
                    ("food", "مطاعم"),
                    ("home", "منزل"),
                    ("beauty", "جمال"),
                    ("sports", "رياضة"),
                    ("books", "كتب"),
                    ("toys", "ألعاب"),
                ],
                default="clothing",
                max_length=20,
            ),
        ),
    ]
