# Generated by Django 4.2.7 on 2025-12-10 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_campaign_sitesettings_contact_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="visitor_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("customer", "عميل"), ("admin", "صاحب متجر")],
                default="customer",
                max_length=20,
            ),
        ),
    ]
