# Generated by Django 4.2.7 on 2025-12-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_sitesettings_visitor_count_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="stores/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("men", "رجالي"),
                    ("women", "نسائي"),
                    ("kids", "أطفال"),
                    ("cosmetics", "كوزمتك"),
                    ("perfumes", "عطور"),
                    ("sports", "رياضية"),
                    ("casual", "كاجوال"),
                    ("formal", "رسمية"),
                    ("accessories", "إكسسوارات"),
                    ("watches", "ساعات"),
                    ("shoes", "أحذية"),
                    ("electronics", "إلكترونيات"),
                    ("beauty", "جمال"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="category",
            field=models.CharField(
                choices=[
                    ("women", "ملابس نسائية"),
                    ("men", "ملابس رجالية"),
                    ("kids", "ملابس أطفال"),
                    ("perfumes", "عطور"),
                    ("cosmetics", "كوزمتك"),
                    ("watches", "ساعات"),
                    ("shoes", "أحذية"),
                    ("clothing", "ملابس عامة"),
                    ("electronics", "إلكترونيات"),
                    ("food", "مطاعم"),
                    ("home", "منزل"),
                    ("beauty", "جمال"),
                    ("sports", "رياضة"),
                    ("books", "كتب"),
                    ("toys", "ألعاب"),
                ],
                default="clothing",
                max_length=20,
            ),
        ),
    ]
