# Generated by Django 4.2.7 on 2025-12-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_store_logo_alter_product_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="size_type",
            field=models.CharField(
                choices=[("symbolic", "رمزية"), ("numeric", "رقمية"), ("none", "بدون")],
                default="symbolic",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="size",
            field=models.CharField(max_length=20),
        ),
    ]
