# Generated by Django 4.2.7 on 2025-12-15 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_migrate_variant_colors"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productvariant",
            name="color",
        ),
    ]
