# Generated by Django 4.2.7 on 2025-12-29 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_productimage_variant"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
