# Generated by Django 4.2.7 on 2026-01-07 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_address_extra_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="address",
            name="plus_code",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
