# Generated by Django 4.2.7 on 2026-01-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_admin_portal"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="free_delivery_threshold",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="primary_color",
            field=models.CharField(blank=True, default="", max_length=7),
        ),
        migrations.AddField(
            model_name="store",
            name="secondary_color",
            field=models.CharField(blank=True, default="", max_length=7),
        ),
        migrations.AddField(
            model_name="store",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "مسودة"),
                    ("ACTIVE", "نشط"),
                    ("DISABLED", "غير نشط"),
                ],
                default="ACTIVE",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="adminauditlog",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="adminloginattempt",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
