# Generated by Django 4.2.7 on 2026-01-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_store_free_delivery_threshold_store_primary_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="currency",
            field=models.CharField(default="IQD", max_length=10),
        ),
        migrations.AddField(
            model_name="store",
            name="delivery_time_unit",
            field=models.CharField(
                blank=True,
                choices=[("hour", "ساعة"), ("day", "يوم")],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="delivery_time_value",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
