# Generated by Django 4.2.7 on 2026-01-12 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_restrict_store_categories"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttributeColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("code", models.CharField(blank=True, max_length=7)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="attributes/colors/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AttributeSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="productvariant",
            name="is_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("men", "رجالي"),
                    ("women", "نسائي"),
                    ("kids", "أطفال"),
                    ("cosmetics", "كوزمتك"),
                    ("perfumes", "عطور"),
                    ("sports", "رياضية"),
                    ("casual", "كاجوال"),
                    ("formal", "رسمية"),
                    ("accessories", "إكسسوارات"),
                    ("watches", "ساعات"),
                    ("shoes", "أحذية"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="category",
            field=models.CharField(
                choices=[
                    ("women", "ملابس نسائية"),
                    ("men", "ملابس رجالية"),
                    ("kids", "ملابس أطفال"),
                    ("clothing", "ملابس عامة"),
                ],
                default="clothing",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="color_attr",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variants",
                to="core.attributecolor",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="size_attr",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variants",
                to="core.attributesize",
            ),
        ),
    ]
