# Generated by Django 4.2.7 on 2026-01-12 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_attributecolor_attributesize_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="color_attr",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="core.attributecolor",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
