# Generated by Django 4.2.7 on 2026-01-13 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_productimage_color_attr_productimage_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="image_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.CreateModel(
            name="ImportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("products_created", models.IntegerField(default=0)),
                ("products_updated", models.IntegerField(default=0)),
                ("variants_created", models.IntegerField(default=0)),
                ("variants_updated", models.IntegerField(default=0)),
                ("images_added", models.IntegerField(default=0)),
                ("errors_count", models.IntegerField(default=0)),
                ("errors_json", models.TextField(blank=True, default="")),
                ("success", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
