# Generated by Django 4.2.7 on 2026-01-22 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_productimage_image_hash_importlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="store_phone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="order",
            name="tracking_number",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "قيد الانتظار"),
                    ("accepted", "تم القبول"),
                    ("packed", "تم التعبئة"),
                    ("preparing", "قيد التجهيز"),
                    ("on_the_way", "في الطريق"),
                    ("delivered", "تم التسليم"),
                    ("canceled", "ملغي"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
