# Generated by Django 4.2.7 on 2026-01-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_order_store_phone_order_tracking_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_phone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_status",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="store",
            name="owner_phone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
