# Generated by Django 4.2.7 on 2026-01-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_order_delivery_phone_order_delivery_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="tracking_token",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
