# Generated by Django 4.2.7 on 2026-01-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_order_tracking_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="delivery_company_phone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
