# Generated by Django 4.2.7 on 2026-02-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_enable_new_arrivals_reports"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="formatted_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="store",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
