# Generated by Django 4.2.7 on 2026-02-01 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_phonereservation_alter_store_owner_alter_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="owner_contact_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        # Skip re-adding unique constraint on user.phone in this migration to
        # avoid crash on environments with duplicate phones. A follow-up
        # migration will enforce uniqueness after data cleanup.
        migrations.CreateModel(
            name="StoreOwnerInvite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("claimed", "claimed"),
                            ("expired", "expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("token", models.CharField(blank=True, default="", max_length=64)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.store"
                    ),
                ),
            ],
        ),
    ]
