# Generated by Django 4.2.7 on 2026-02-02 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_store_owner_contact_name_alter_user_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
