# Generated by Django 4.2.7 on 2026-02-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_alter_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="storeownerinvite",
            name="claimed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
