# Generated by Django 4.2.7 on 2026-02-03 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_trim_store_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "مسودة"),
                    ("ACTIVE", "نشط"),
                    ("DISABLED", "غير نشط"),
                ],
                db_index=True,
                default="DRAFT",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.product"
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="category",
            field=models.CharField(
                choices=[
                    ("women", "ملابس نسائية"),
                    ("men", "ملابس رجالية"),
                    ("kids", "ملابس أطفال"),
                    ("perfumes", "عطور"),
                    ("cosmetics", "كوزمتك"),
                    ("watches", "ساعات"),
                    ("shoes", "أحذية"),
                    ("clothing", "ملابس عامة"),
                ],
                default="clothing",
                max_length=20,
            ),
        ),
    ]
