# Generated by Django 4.2.28 on 2026-02-04 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_store_owner_user_foreignkey"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="order",
            new_name="core_order_created_912d27_idx",
            old_name="order_created_idx",
        ),
        migrations.RenameIndex(
            model_name="order",
            new_name="core_order_store_i_a11d10_idx",
            old_name="order_store_idx",
        ),
        migrations.RenameIndex(
            model_name="order",
            new_name="core_order_user_id_f84106_idx",
            old_name="order_user_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="core_produc_status_b17a10_idx",
            old_name="product_status_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="core_produc_store_i_8aff85_idx",
            old_name="product_store_idx",
        ),
        migrations.RenameIndex(
            model_name="productimage",
            new_name="core_produc_product_b0d6d1_idx",
            old_name="image_product_idx",
        ),
        migrations.RenameIndex(
            model_name="productvariant",
            new_name="core_produc_product_76849a_idx",
            old_name="variant_product_idx",
        ),
    ]
