# Generated by Django 4.2.28 on 2026-02-09 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0045_rename_order_created_idx_core_order_created_912d27_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="fit_type",
            field=models.CharField(
                choices=[
                    ("small", "قالب صغير"),
                    ("standard", "قالب قياسي"),
                    ("oversized", "قالب واسع"),
                ],
                default="standard",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="video_file",
            field=models.FileField(blank=True, null=True, upload_to="products/videos/"),
        ),
        migrations.AddField(
            model_name="productimage",
            name="video_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
