# Generated by Django 4.2.28 on 2026-02-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_error_log"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="errorlog",
            new_name="core_errorl_source_d2bc84_idx",
            old_name="core_error_source_idx",
        ),
        migrations.RenameIndex(
            model_name="errorlog",
            new_name="core_errorl_file_pa_4e5160_idx",
            old_name="core_error_file_idx",
        ),
        migrations.RenameIndex(
            model_name="errorlog",
            new_name="core_errorl_line_nu_ee7719_idx",
            old_name="core_error_line_idx",
        ),
        migrations.AddField(
            model_name="product",
            name="allow_negotiation",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="minimum_acceptable_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
