# Generated by Django 4.2.28 on 2026-02-15 19:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_cartitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name="cartitem",
            new_name="core_cartit_user_id_c79c77_idx",
            old_name="core_cartitem_user_idx",
        ),
        migrations.RenameIndex(
            model_name="cartitem",
            new_name="core_cartit_product_70953e_idx",
            old_name="core_cartitem_product_idx",
        ),
        migrations.RenameIndex(
            model_name="cartitem",
            new_name="core_cartit_variant_db1378_idx",
            old_name="core_cartitem_variant_idx",
        ),
        migrations.AddField(
            model_name="product",
            name="alert_note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="store",
            name="negotiation_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="store",
            name="negotiation_max_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="proposal_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="apprating",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
