# Generated by Django 4.2.7 on 2026-03-06 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_product_show_store_rating_storerating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="is_featured",
            field=models.BooleanField(default=False, verbose_name="منتج مميز"),
        ),
    ]
