# Generated by Django 4.2.7 on 2026-03-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0053_alter_product_is_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_on_offer",
            field=models.BooleanField(default=False, verbose_name="في العروض"),
        ),
        migrations.AddField(
            model_name="product",
            name="offer_badge_text",
            field=models.CharField(blank=True, max_length=50, verbose_name="نص الشارة"),
        ),
        migrations.AddField(
            model_name="product",
            name="offer_discount_percent",
            field=models.IntegerField(default=0, verbose_name="نسبة الخصم"),
        ),
        migrations.AddField(
            model_name="product",
            name="offer_end",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="نهاية العرض"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="offer_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="سعر العرض",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="offer_start",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="بداية العرض"
            ),
        ),
    ]
