# Generated by Django 4.2.7 on 2026-03-19 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0055_campaign_action_url_default_and_backfill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
