# Generated by Django 4.2.28 on 2026-02-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="ads/banners/")),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("product", "Product"),
                            ("category", "Category"),
                            ("store", "Store"),
                            ("url", "URL"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("link_target", models.CharField(blank=True, max_length=200)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_dismissible", models.BooleanField(default=False)),
                ("priority", models.IntegerField(default=0)),
                (
                    "placement",
                    models.CharField(
                        choices=[
                            ("home_top", "Home Top"),
                            ("home_middle", "Home Middle"),
                            ("home_bottom", "Home Bottom"),
                        ],
                        default="home_top",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-priority", "-updated_at"),
                "indexes": [
                    models.Index(
                        fields=["placement"], name="ads_banner_placeme_53be51_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="ads_banner_is_acti_a28bdc_idx"
                    ),
                ],
            },
        ),
    ]
