# Generated by Django 4.2.7 on 2026-03-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0003_update_advertisement_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="advertisement",
            options={"ordering": (["order", "-created_at"],)},
        ),
        migrations.RenameIndex(
            model_name="advertisement",
            new_name="ads_adverti_positio_43f588_idx",
            old_name="ads_adverti_position_9f0b7c_idx",
        ),
        migrations.RenameIndex(
            model_name="advertisement",
            new_name="ads_adverti_is_acti_a1a936_idx",
            old_name="ads_adverti_is_activ_7b5b58_idx",
        ),
        migrations.AddField(
            model_name="advertisement",
            name="auto_slide",
            field=models.BooleanField(default=True, verbose_name="تقليب تلقائي"),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="media_type",
            field=models.CharField(
                choices=[("image", "صورة"), ("video", "فيديو")],
                default="image",
                max_length=10,
                verbose_name="نوع الوسائط",
            ),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="open_in_app",
            field=models.BooleanField(default=True, verbose_name="فتح داخل التطبيق"),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="slide_duration",
            field=models.IntegerField(default=5, verbose_name="مدة العرض (ثواني)"),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to="ads/videos/", verbose_name="فيديو"
            ),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="video_url",
            field=models.URLField(blank=True, verbose_name="رابط فيديو خارجي"),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="description",
            field=models.TextField(blank=True, verbose_name="الوصف"),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="end_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ الانتهاء"
            ),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="ads/", verbose_name="الصورة"
            ),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="نشط"),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="order",
            field=models.IntegerField(default=0, verbose_name="الترتيب"),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="title",
            field=models.CharField(max_length=200, verbose_name="العنوان"),
        ),
    ]
