# Generated by Django 4.2.7 on 2026-03-07 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_featured",
            field=models.BooleanField(default=False, verbose_name="منتج مميز"),
        ),
    ]
